// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezpvwavmgilqathondtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6cHZ3YXZtZ2lscWF0aG9uZHRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMjI1MDcsImV4cCI6MjA2NDU5ODUwN30.wOJ8o7DHHnJfxLFhcodU1xUGtqt3Q9r9NKoQrag5HMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);